### ISSUE TITLE
New feature help

### ISSUE THREAD

**Issue by jbb26354** [wagnva/NotificationMaker#1]
Hello, I would like to add a new feature to the app - the ability to reorder items by drag and drop. 

I would just like some advice on the right way to do that.

Thank you.

**Comment by wagnva** [comment]
Hey,

I am happy that you want to add features to my app.
Unfortunately i am currently in the process of rewriting the app, so any changes made by you would be lost.

The version here is also outdated.

Thank you for interest though

**Comment by jbb26354** [comment]
really!! wonderful!   ...will you be adding drag-and-drop reoredering...?
